name: project cicd flow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: '1.11'
        distribution: 'adopt'
        cache: maven
    
    - name: Build with Maven
      run: mvn clean install
    
    - name: Show all images on local Docker before
      run: docker images
      
    - name: Create image on local Docker
      run: docker build -t spring-github-actions-simple-project .
      
    - name: Show all images on local Docker after
      run: docker images